
# k8s/prod-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app-prod
  labels:
    app: sample-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-app
  template:
    metadata:
      labels:
        app: sample-web-app
    spec:
      containers:
        - name: sample-web-app
          image: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/sample-web-app:prod
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-service-prod
spec:
  selector:
    app: sample-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
